### ISSUE TITLE
v4.0のフィードバック

### ISSUE THREAD

**Issue by nishiyamaosamu** [satokifuruya/QiitaApp#10]
- シングルトンであれば、初期化出来ないようにしておいてもよいかも？
  https://github.com/satokifuruya/QiitaApp/blob/v_4.0/QiitaApp/BookmarkArticle.swift#L14
  参照：http://egg-is-world.com/2016/01/18/swift-2-singleton/
- webviewを開く時に、下に黒い部分が現れる→修正を。（こういうバグがiosでは良くある。）

全体的にとても良いと思いますー。

**Comment by satokifuruya** [comment]
@nishiyamaosamu 
ご確認ありがとうございます！

> シングルトンであれば、初期化出来ないようにしておいてもよいかも？

そうですね、忘れていました…
private init を定義します！

> webviewを開く時に、下に黒い部分が現れる→修正を。

指摘されるまで、認識していなかったです…
AutoLayoutの設定を修正しました！
